/*
 * This source file was generated by the Gradle 'init' task
 */
package labi_java.laba2;

import labi_java.laba2.classes.*;

public class App {
    public static void main(String[] args) {
        ClassRoom class1 = new ClassRoom(new BadPupil(), new BadPupil());
        class1.GetRoundGrade();
        System.out.println("Average grade: " + class1.GetRoundGrade());
        System.out.println("Total students: " + ClassRoom.GetPupilsCount());
    }
}
